[package]
name = "visit_diff"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"
workspace = ".."

[dependencies]
void = "1"
serde = "1.0.87"
visit_diff_derive = { path = "../diff_derive", optional = true }
itertools = "0.8.0"

[features]
default = ["visit_diff_derive"]
