[package]
name = "diffwalk"
version = "0.1.0"
authors = ["Cliff L. Biffle <code@cliffle.com>"]
edition = "2018"
workspace = ".."

[dependencies]
void = "1"
serde = "1.0.87"
diffwalk_derive = { path = "../diff_derive" }
itertools = "0.8.0"
